// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package company;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * ServiceAction enum defines the type of action to be performed on the service.
   * </pre>
   *
   * Protobuf enum {@code company.ServiceAction}
   */
  public enum ServiceAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>CREATE = 1;</code>
     */
    CREATE(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2),
    /**
     * <code>START = 3;</code>
     */
    START(3),
    /**
     * <code>STOP = 4;</code>
     */
    STOP(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>CREATE = 1;</code>
     */
    public static final int CREATE_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;
    /**
     * <code>START = 3;</code>
     */
    public static final int START_VALUE = 3;
    /**
     * <code>STOP = 4;</code>
     */
    public static final int STOP_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServiceAction valueOf(int value) {
      return forNumber(value);
    }

    public static ServiceAction forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return CREATE;
        case 2: return DELETE;
        case 3: return START;
        case 4: return STOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceAction>() {
            public ServiceAction findValueByNumber(int number) {
              return ServiceAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return company.Service.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceAction[] VALUES = values();

    public static ServiceAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:company.ServiceAction)
  }

  /**
   * <pre>
   * OperationStatus enum defines possible outcomes of the requested operation.
   * </pre>
   *
   * Protobuf enum {@code company.OperationStatus}
   */
  public enum OperationStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    STATUS_UNKNOWN(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>FAILURE = 2;</code>
     */
    FAILURE(2),
    /**
     * <code>NOT_FOUND = 3;</code>
     */
    NOT_FOUND(3),
    /**
     * <code>ALREADY_EXISTS = 4;</code>
     */
    ALREADY_EXISTS(4),
    /**
     * <code>INVALID_OPERATION = 5;</code>
     */
    INVALID_OPERATION(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_UNKNOWN = 0;</code>
     */
    public static final int STATUS_UNKNOWN_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAILURE = 2;</code>
     */
    public static final int FAILURE_VALUE = 2;
    /**
     * <code>NOT_FOUND = 3;</code>
     */
    public static final int NOT_FOUND_VALUE = 3;
    /**
     * <code>ALREADY_EXISTS = 4;</code>
     */
    public static final int ALREADY_EXISTS_VALUE = 4;
    /**
     * <code>INVALID_OPERATION = 5;</code>
     */
    public static final int INVALID_OPERATION_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OperationStatus valueOf(int value) {
      return forNumber(value);
    }

    public static OperationStatus forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNKNOWN;
        case 1: return SUCCESS;
        case 2: return FAILURE;
        case 3: return NOT_FOUND;
        case 4: return ALREADY_EXISTS;
        case 5: return INVALID_OPERATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationStatus>() {
            public OperationStatus findValueByNumber(int number) {
              return OperationStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return company.Service.getDescriptor().getEnumTypes().get(1);
    }

    private static final OperationStatus[] VALUES = values();

    public static OperationStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:company.OperationStatus)
  }

  public interface ServiceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:company.ServiceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the service.
     * </pre>
     *
     * <code>string service_id = 1;</code>
     */
    java.lang.String getServiceId();
    /**
     * <pre>
     * Unique identifier for the service.
     * </pre>
     *
     * <code>string service_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <pre>
     * Action to be performed on the service.
     * </pre>
     *
     * <code>.company.ServiceAction action = 2;</code>
     */
    int getActionValue();
    /**
     * <pre>
     * Action to be performed on the service.
     * </pre>
     *
     * <code>.company.ServiceAction action = 2;</code>
     */
    company.Service.ServiceAction getAction();
  }
  /**
   * <pre>
   * ServiceRequest message is used by the client to request a service action.
   * </pre>
   *
   * Protobuf type {@code company.ServiceRequest}
   */
  public  static final class ServiceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:company.ServiceRequest)
      ServiceRequestOrBuilder {
    // Use ServiceRequest.newBuilder() to construct.
    private ServiceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceRequest() {
      serviceId_ = "";
      action_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServiceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return company.Service.internal_static_company_ServiceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return company.Service.internal_static_company_ServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              company.Service.ServiceRequest.class, company.Service.ServiceRequest.Builder.class);
    }

    public static final int SERVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object serviceId_;
    /**
     * <pre>
     * Unique identifier for the service.
     * </pre>
     *
     * <code>string service_id = 1;</code>
     */
    public java.lang.String getServiceId() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique identifier for the service.
     * </pre>
     *
     * <code>string service_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <pre>
     * Action to be performed on the service.
     * </pre>
     *
     * <code>.company.ServiceAction action = 2;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <pre>
     * Action to be performed on the service.
     * </pre>
     *
     * <code>.company.ServiceAction action = 2;</code>
     */
    public company.Service.ServiceAction getAction() {
      company.Service.ServiceAction result = company.Service.ServiceAction.valueOf(action_);
      return result == null ? company.Service.ServiceAction.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceId_);
      }
      if (action_ != company.Service.ServiceAction.UNKNOWN.getNumber()) {
        output.writeEnum(2, action_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceId_);
      }
      if (action_ != company.Service.ServiceAction.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof company.Service.ServiceRequest)) {
        return super.equals(obj);
      }
      company.Service.ServiceRequest other = (company.Service.ServiceRequest) obj;

      boolean result = true;
      result = result && getServiceId()
          .equals(other.getServiceId());
      result = result && action_ == other.action_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceId().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static company.Service.ServiceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static company.Service.ServiceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static company.Service.ServiceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static company.Service.ServiceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static company.Service.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static company.Service.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(company.Service.ServiceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ServiceRequest message is used by the client to request a service action.
     * </pre>
     *
     * Protobuf type {@code company.ServiceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:company.ServiceRequest)
        company.Service.ServiceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return company.Service.internal_static_company_ServiceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return company.Service.internal_static_company_ServiceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                company.Service.ServiceRequest.class, company.Service.ServiceRequest.Builder.class);
      }

      // Construct using company.Service.ServiceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serviceId_ = "";

        action_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return company.Service.internal_static_company_ServiceRequest_descriptor;
      }

      public company.Service.ServiceRequest getDefaultInstanceForType() {
        return company.Service.ServiceRequest.getDefaultInstance();
      }

      public company.Service.ServiceRequest build() {
        company.Service.ServiceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public company.Service.ServiceRequest buildPartial() {
        company.Service.ServiceRequest result = new company.Service.ServiceRequest(this);
        result.serviceId_ = serviceId_;
        result.action_ = action_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof company.Service.ServiceRequest) {
          return mergeFrom((company.Service.ServiceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(company.Service.ServiceRequest other) {
        if (other == company.Service.ServiceRequest.getDefaultInstance()) return this;
        if (!other.getServiceId().isEmpty()) {
          serviceId_ = other.serviceId_;
          onChanged();
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        company.Service.ServiceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (company.Service.ServiceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object serviceId_ = "";
      /**
       * <pre>
       * Unique identifier for the service.
       * </pre>
       *
       * <code>string service_id = 1;</code>
       */
      public java.lang.String getServiceId() {
        java.lang.Object ref = serviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier for the service.
       * </pre>
       *
       * <code>string service_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        java.lang.Object ref = serviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier for the service.
       * </pre>
       *
       * <code>string service_id = 1;</code>
       */
      public Builder setServiceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the service.
       * </pre>
       *
       * <code>string service_id = 1;</code>
       */
      public Builder clearServiceId() {
        
        serviceId_ = getDefaultInstance().getServiceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the service.
       * </pre>
       *
       * <code>string service_id = 1;</code>
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceId_ = value;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <pre>
       * Action to be performed on the service.
       * </pre>
       *
       * <code>.company.ServiceAction action = 2;</code>
       */
      public int getActionValue() {
        return action_;
      }
      /**
       * <pre>
       * Action to be performed on the service.
       * </pre>
       *
       * <code>.company.ServiceAction action = 2;</code>
       */
      public Builder setActionValue(int value) {
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Action to be performed on the service.
       * </pre>
       *
       * <code>.company.ServiceAction action = 2;</code>
       */
      public company.Service.ServiceAction getAction() {
        company.Service.ServiceAction result = company.Service.ServiceAction.valueOf(action_);
        return result == null ? company.Service.ServiceAction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Action to be performed on the service.
       * </pre>
       *
       * <code>.company.ServiceAction action = 2;</code>
       */
      public Builder setAction(company.Service.ServiceAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Action to be performed on the service.
       * </pre>
       *
       * <code>.company.ServiceAction action = 2;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:company.ServiceRequest)
    }

    // @@protoc_insertion_point(class_scope:company.ServiceRequest)
    private static final company.Service.ServiceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new company.Service.ServiceRequest();
    }

    public static company.Service.ServiceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceRequest>
        PARSER = new com.google.protobuf.AbstractParser<ServiceRequest>() {
      public ServiceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceRequest> getParserForType() {
      return PARSER;
    }

    public company.Service.ServiceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:company.ServiceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The outcome of the operation.
     * </pre>
     *
     * <code>.company.OperationStatus status = 1;</code>
     */
    int getStatusValue();
    /**
     * <pre>
     * The outcome of the operation.
     * </pre>
     *
     * <code>.company.OperationStatus status = 1;</code>
     */
    company.Service.OperationStatus getStatus();

    /**
     * <pre>
     * Additional information about the outcome.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Additional information about the outcome.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * ServiceResponse message is used by the server to respond to the client.
   * </pre>
   *
   * Protobuf type {@code company.ServiceResponse}
   */
  public  static final class ServiceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:company.ServiceResponse)
      ServiceResponseOrBuilder {
    // Use ServiceResponse.newBuilder() to construct.
    private ServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceResponse() {
      status_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServiceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return company.Service.internal_static_company_ServiceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return company.Service.internal_static_company_ServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              company.Service.ServiceResponse.class, company.Service.ServiceResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     * The outcome of the operation.
     * </pre>
     *
     * <code>.company.OperationStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * The outcome of the operation.
     * </pre>
     *
     * <code>.company.OperationStatus status = 1;</code>
     */
    public company.Service.OperationStatus getStatus() {
      company.Service.OperationStatus result = company.Service.OperationStatus.valueOf(status_);
      return result == null ? company.Service.OperationStatus.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Additional information about the outcome.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Additional information about the outcome.
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != company.Service.OperationStatus.STATUS_UNKNOWN.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != company.Service.OperationStatus.STATUS_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof company.Service.ServiceResponse)) {
        return super.equals(obj);
      }
      company.Service.ServiceResponse other = (company.Service.ServiceResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static company.Service.ServiceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static company.Service.ServiceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static company.Service.ServiceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static company.Service.ServiceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static company.Service.ServiceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static company.Service.ServiceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static company.Service.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static company.Service.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(company.Service.ServiceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ServiceResponse message is used by the server to respond to the client.
     * </pre>
     *
     * Protobuf type {@code company.ServiceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:company.ServiceResponse)
        company.Service.ServiceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return company.Service.internal_static_company_ServiceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return company.Service.internal_static_company_ServiceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                company.Service.ServiceResponse.class, company.Service.ServiceResponse.Builder.class);
      }

      // Construct using company.Service.ServiceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return company.Service.internal_static_company_ServiceResponse_descriptor;
      }

      public company.Service.ServiceResponse getDefaultInstanceForType() {
        return company.Service.ServiceResponse.getDefaultInstance();
      }

      public company.Service.ServiceResponse build() {
        company.Service.ServiceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public company.Service.ServiceResponse buildPartial() {
        company.Service.ServiceResponse result = new company.Service.ServiceResponse(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof company.Service.ServiceResponse) {
          return mergeFrom((company.Service.ServiceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(company.Service.ServiceResponse other) {
        if (other == company.Service.ServiceResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        company.Service.ServiceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (company.Service.ServiceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * The outcome of the operation.
       * </pre>
       *
       * <code>.company.OperationStatus status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * The outcome of the operation.
       * </pre>
       *
       * <code>.company.OperationStatus status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The outcome of the operation.
       * </pre>
       *
       * <code>.company.OperationStatus status = 1;</code>
       */
      public company.Service.OperationStatus getStatus() {
        company.Service.OperationStatus result = company.Service.OperationStatus.valueOf(status_);
        return result == null ? company.Service.OperationStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The outcome of the operation.
       * </pre>
       *
       * <code>.company.OperationStatus status = 1;</code>
       */
      public Builder setStatus(company.Service.OperationStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The outcome of the operation.
       * </pre>
       *
       * <code>.company.OperationStatus status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Additional information about the outcome.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Additional information about the outcome.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Additional information about the outcome.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional information about the outcome.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional information about the outcome.
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:company.ServiceResponse)
    }

    // @@protoc_insertion_point(class_scope:company.ServiceResponse)
    private static final company.Service.ServiceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new company.Service.ServiceResponse();
    }

    public static company.Service.ServiceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceResponse>() {
      public ServiceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceResponse> getParserForType() {
      return PARSER;
    }

    public company.Service.ServiceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_ServiceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_ServiceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_company_ServiceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_company_ServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\007company\"L\n\016ServiceReque" +
      "st\022\022\n\nservice_id\030\001 \001(\t\022&\n\006action\030\002 \001(\0162\026" +
      ".company.ServiceAction\"L\n\017ServiceRespons" +
      "e\022(\n\006status\030\001 \001(\0162\030.company.OperationSta" +
      "tus\022\017\n\007message\030\002 \001(\t*I\n\rServiceAction\022\013\n" +
      "\007UNKNOWN\020\000\022\n\n\006CREATE\020\001\022\n\n\006DELETE\020\002\022\t\n\005ST" +
      "ART\020\003\022\010\n\004STOP\020\004*y\n\017OperationStatus\022\022\n\016ST" +
      "ATUS_UNKNOWN\020\000\022\013\n\007SUCCESS\020\001\022\013\n\007FAILURE\020\002" +
      "\022\r\n\tNOT_FOUND\020\003\022\022\n\016ALREADY_EXISTS\020\004\022\025\n\021I" +
      "NVALID_OPERATION\020\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_company_ServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_company_ServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_ServiceRequest_descriptor,
        new java.lang.String[] { "ServiceId", "Action", });
    internal_static_company_ServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_company_ServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_company_ServiceResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
